/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nick Broad (https://sketchfab.com/nickbroad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-and-mouse-c6e193ac304e477aaed7946289dbe150
Title: Laptop and mouse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('models/Laptop.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Buttons_LaptopKeys_0.geometry}
        material={materials.LaptopKeys}
        position={[12.411, 6.664, 13.904]}
        rotation={[-1.541, -0.082, 1.968]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_MatTrans_0.geometry}
        material={materials.PaletteMaterial001}
        position={[5.951, 0.223, 31.084]}
        rotation={[-Math.PI / 2, 0, -1.222]}
        scale={[10.949, 14.207, 0.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_MouseMatte_0.geometry}
        material={materials.MouseMatte}
        position={[6.237, 0.243, 30.979]}
        rotation={[-Math.PI / 2, 0, -1.222]}
        scale={[10.533, 13.668, 0.221]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LaptopKeyboard_LaptopRed_0.geometry}
        material={materials.PaletteMaterial002}
        position={[-3.054, 5.015, -0.558]}
        rotation={[-1.541, -0.082, 1.921]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LaptopLid_LaptopLid_0.geometry}
        material={materials.LaptopLid}
        position={[9.799, 7.015, -5.236]}
        rotation={[2.891, 1.211, -2.907]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseUSB_MouseCable_0.geometry}
        material={materials.MouseCable}
        position={[-2.979, 5.015, -0.352]}
        rotation={[-1.541, -0.082, 1.921]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseUSB_MouseUSB_0.geometry}
        material={materials.MouseUSB}
        position={[-2.979, 5.015, -0.352]}
        rotation={[-1.541, -0.082, 1.921]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('models/Laptop.glb')

export default Laptop;